# Generated by Django 5.1 on 2024-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='instructons',
        ),
        migrations.AddField(
            model_name='recipes',
            name='instructions',
            field=models.TextField(default='No instrucitions available.'),
        ),
    ]
